/* =====================================================================
   js/reglesEffets.js — Le vocabulaire du graphe : nœuds, effets, déclencheurs

   Les concepts que l'atelier sait reconnaître, groupés par famille, et les
   expressions qui les repèrent dans le texte d'une carte. Tout est table :
   ajouter un effet, c'est ajouter une ligne, jamais une branche de code.
   ===================================================================== */

/* 1. Nœuds et groupes du graphe */
const GROUPS = {
  cartes:      {label:'Cartes',        color:'#59b0e0'},
  cimetiere:   {label:'Cimetière',     color:'#a077cf'},
  board:       {label:'Développement', color:'#4fb07a'},
  mana:        {label:'Mana',          color:'#d3a441'},
  sorts:       {label:'Sorts',         color:'#57c9c4'},
  interaction: {label:'Interaction',   color:'#d3573f'},
  stax:        {label:'Contrôle',      color:'#8d93a6'},
  vie:         {label:'Points de vie', color:'#e07a9c'},
  combat:      {label:'Combat',        color:'#e08a3f'},
  protection:  {label:'Protection',    color:'#e6dcc0'},
  timing:      {label:'Timing',        color:'#7f8fd0'}
};

const NODES = [
  ['PIOCHE','Pioche','cartes'],
  ['IMPULSE','Filtrage / impulsion','cartes'],
  ['TUTEUR','Tuteur','cartes'],
  ['CYCLE','Cycle','cartes'],
  ['REVELATION','Révélation','cartes'],
  ['MAIN_VIDE','Main vide','cartes'],
  ['RECURSION','Récursion','cartes'],
  ['MILL','Meule','cimetiere'],
  ['DEFAUSSE','Défausse','cimetiere'],
  ['MIS_AU_CIMETIERE','Mise au cimetière','cimetiere'],
  ['SACRIFICE','Sacrifice','cimetiere'],
  ['MORT','Mort de créature','cimetiere'],
  ['MORT_SOI','Mort de cette carte','cimetiere'],
  ['LTB','Départ du champ de bataille','cimetiere'],
  ['JETON','Jeton de créature','board'],
  ['MARQUEUR','Marqueur +1/+1','board'],
  ['MARQUEUR_M1M1','Marqueur -1/-1','board'],
  ['MARQUEUR_AUTRE','Autre marqueur','board'],
  ['MARQUEUR_RETIRE','Retrait de marqueur','board'],
  ['PROLIFERATION','Prolifération','board'],
  ['COPIE','Copie','board'],
  ['BLINK','Blink','board'],
  ['ETB','Arrivée en jeu','board'],
  ['ETB_SOI','Arrivée de cette carte','board'],
  ['ETB_CIMETIERE','Arrivée depuis le cimetière','board'],
  ['ETB_EXIL','Arrivée depuis l\'exil','board'],
  ['ETB_BIBLIO','Arrivée depuis la bibliothèque','board'],
  ['TRANSFORMATION','Transformation','board'],
  ['FACE_VISIBLE','Retournement face visible','board'],
  ['ATTACHEMENT','Attachement','board'],
  ['GAIN_CONTROLE','Gain de contrôle','board'],
  ['TERRAIN','Terrain (landfall)','mana'],
  ['TERRAIN_JOUE','Terrain joué','mana'],
  ['RAMP','Ramp','mana'],
  ['TRESOR','Trésor','mana'],
  ['MANA','Mana','mana'],
  ['MANA_DEPENSE','Mana dépensé','mana'],
  ['UNTAP','Dégagement','mana'],
  ['REDUCTION','Réduction de coût','mana'],
  ['ENERGIE','Énergie','mana'],
  ['EXPERIENCE','Expérience','mana'],
  ['LANCEMENT','Lancement de sort','sorts'],
  ['LANCEMENT_SOI','Lancement de cette carte','sorts'],
  ['SORT_RESOUT','Résolution de sort','sorts'],
  ['CONTRESORT','Contresort','sorts'],
  ['DEVIENT_CIBLE','Devient une cible','sorts'],
  ['CAPACITE_ACTIVEE','Capacité activée','sorts'],
  ['CAPACITE_DECLENCHEE','Capacité déclenchée','sorts'],
  ['DESTRUCTION','Destruction','interaction'],
  ['EXIL','Exil','interaction'],
  ['BOUNCE','Renvoi en main','interaction'],
  ['MIS_EN_BIBLIO','Mise en bibliothèque','interaction'],
  ['DEGATS','Dégâts','interaction'],
  ['DEGATS_SUBIS','Blessures subies','interaction'],
  ['ENGAGEMENT','Engagement','stax'],
  ['STAX','Stax','stax'],
  ['TAXE','Taxe','stax'],
  ['PERTE_VIE','Perte de vie','vie'],
  ['GAIN_VIE','Gain de vie','vie'],
  ['POISON','Poison','vie'],
  ['SEUIL_VIE','Seuil de points de vie','vie'],
  ['ATTAQUE','Attaque','combat'],
  ['ATTAQUE_SEULE','Attaque seule','combat'],
  ['BLOCAGE','Blocage','combat'],
  ['DEVIENT_BLOQUEE','Devient bloquée','combat'],
  ['DEGATS_COMBAT_JOUEUR','Blessures de combat au joueur','combat'],
  ['DEGATS_COMBAT_CREATURE','Blessures de combat à une créature','combat'],
  ['DEBUT_COMBAT','Début du combat','combat'],
  ['FIN_COMBAT','Fin du combat','combat'],
  ['BOOST','Boost temporaire','combat'],
  ['VOL','Vol','combat'],
  ['PIETINEMENT','Piétinement','combat'],
  ['MENACE','Menace','combat'],
  ['IMBLOCABLE','Imblocable','combat'],
  ['CELERITE','Célérité','combat'],
  ['VIGILANCE','Vigilance','combat'],
  ['INDESTRUCTIBLE','Indestructible','protection'],
  ['LINCEUL','Linceul','protection'],
  ['PROTECTION','Protection / ward','protection'],
  ['ENTRETIEN','Entretien','timing'],
  ['ETAPE_PIOCHE','Étape de pioche','timing'],
  ['PHASE_PRINCIPALE','Phase principale','timing'],
  ['FIN_TOUR','Fin du tour','timing'],
  ['DEBUT_TOUR','Début du tour','timing'],
  ['TOUR_SUPPLEMENTAIRE','Tour supplémentaire','timing'],
  ['JOUR_NUIT','Jour et nuit','timing'],
  ['CHAPITRE_SAGA','Chapitre de saga','timing'],
  ['MONARQUE','Monarque / initiative','timing'],
  ['DONJON','Donjon','timing'],
  ['DE','Dé ou pile ou face','timing'],
  ['STATIQUE','Effet continu','timing']
];

const NODE = {};
NODES.forEach((n,i)=>NODE[n[0]]={id:n[0],label:n[1],group:n[2],idx:i});

/* Arcs "règles du jeu" : ce qu'un effet permet mécaniquement d'enchaîner */
const IMPLICIT = [
  ['JETON','ETB'],['COPIE','ETB'],['BLINK','ETB'],['RECURSION','ETB'],['LANCEMENT','ETB'],
  ['COPIE','ETB_SOI'],['BLINK','ETB_SOI'],['RECURSION','ETB_SOI'],['LANCEMENT','ETB_SOI'],
  ['SACRIFICE','MORT_SOI'],['DESTRUCTION','MORT_SOI'],
  ['UNTAP','ENGAGEMENT'],['TRESOR','MANA'],['RAMP','MANA'],['TERRAIN','RAMP'],['MANA','LANCEMENT'],
  ['SACRIFICE','MORT'],['DESTRUCTION','MORT'],['MILL','RECURSION'],['DEFAUSSE','RECURSION'],
  ['MARQUEUR','BOOST'],['REDUCTION','LANCEMENT'],['RECURSION','LANCEMENT'],['ETB','SACRIFICE'],
  ['MORT','MIS_AU_CIMETIERE'],['DEFAUSSE','MIS_AU_CIMETIERE'],['MILL','MIS_AU_CIMETIERE'],
  ['MIS_AU_CIMETIERE','RECURSION'],['MORT','LTB'],['EXIL','LTB'],['BOUNCE','LTB'],['DESTRUCTION','LTB'],
  ['ETB_CIMETIERE','ETB'],['ETB_EXIL','ETB'],['ETB_BIBLIO','ETB'],['TERRAIN_JOUE','TERRAIN'],
  ['ATTAQUE','DEGATS_COMBAT_JOUEUR'],['DEGATS_COMBAT_JOUEUR','DEGATS'],['DEGATS_COMBAT_CREATURE','DEGATS'],
  ['BLOCAGE','DEGATS_COMBAT_CREATURE'],['DEGATS','DEGATS_SUBIS'],['DEGATS_COMBAT_JOUEUR','PERTE_VIE'],
  ['PROLIFERATION','MARQUEUR'],['MARQUEUR_RETIRE','MARQUEUR'],['CYCLE','DEFAUSSE'],['CYCLE','PIOCHE'],
  ['LANCEMENT','SORT_RESOUT'],['SORT_RESOUT','ETB'],['CAPACITE_ACTIVEE','ENGAGEMENT'],
  ['MANA_DEPENSE','MANA'],['ENERGIE','MANA']
];

/* Règles d'extraction : effets produits */
const EFFECT_RULES = [
  ['BLINK',      /exile (?:it|them|this creature|another target|up to one other target|target)[^.]{0,70}?(?:,\s*then|\s+and then|\s*,\s*)\s*return[^.]{0,60}battlefield/],
  ['BLINK',      /exile [^.]{0,60}you control[^.]{0,60}return (?:it|those cards|that card)[^.]{0,50}battlefield/],
  ['RECURSION',  /return[^.]{0,70}(?:card|cards)[^.]{0,30}from (?:a|your|target player's|their) graveyard/],
  ['RECURSION',  /(?:cast|play)[^.]{0,40}from (?:your|a) graveyard|gains? flashback|has escape/],
  ['RECURSION',  /return enchanted creature card/],
  ['RECURSION',  /return (?:that|it|those) cards? to the battlefield/],
  ['COPIE',      /triggers an additional time/],
  ['RAMP',       /search your library for[^.]{0,60}land[^.]{0,60}onto the battlefield/],
  ['RAMP',       /put a land card from your hand onto the battlefield/],
  ['TUTEUR',     /search your library for/],
  ['PIOCHE',     /draws? (?:a card|two cards|three cards|\w+ additional cards|two additional cards|cards)/],
  ['IMPULSE',    /\bscry\b|\bsurveil\b|look at the top|exile the top (?:card|\w+ cards)? ?of your library/],
  ['IMPULSE',    /play (?:lands and )?(?:cast )?spells from the top of your library|may (?:play|cast) (?:them|those cards|the exiled cards?|it)\b[^.]{0,30}(?:this turn|until)/],
  ['IMPULSE',    /exile[^.]{0,60}from among (?:the )?(?:revealed|them)/],
  ['MILL',       /\bmills?\b|puts? the top[^.]{0,40}into (?:their|his or her) graveyard/],
  ['DEFAUSSE',   /discards?/],
  ['SACRIFICE',  /sacrifices?/],
  ['TRESOR',     /treasure token/],
  ['JETON',      /creates? [^.]{0,60}creature token/],
  ['JETON',      /creates? (?:a|an|x|one|two|three|six|\d+)[^.]{0,40}token/],
  ['MARQUEUR',   /\+1\/\+1 counter|\bproliferate\b/],
  ['COPIE',      /token that's a copy|copy (?:that|target) (?:ability|spell)|copies of/],
  ['MANA',       /add \{|adds an additional|add one mana|adds? (?:one|two|three) mana/],
  ['UNTAP',      /untaps?\b/],
  ['TERRAIN',    /play an additional land/],
  ['REDUCTION',  /costs? \{?\w?\}? less to cast/],
  ['CONTRESORT', /counter target/],
  ['DESTRUCTION',/destroys?\b/],
  ['EXIL',       /exiles?\b/],
  ['BOUNCE',     /return [^.]{0,70}to (?:its|their) owners?['\u2019]?s? hands?|return [^.]{0,70}to (?:your|their) hands?|shuffles it into their library/],
  ['DEGATS',     /deals? \d+ damage|deals damage equal|deals \w+ damage|\bfights?\b/],
  ['PERTE_VIE',  /(?:each opponent|target player|that player|opponents) loses? \d+ life|loses? \d+ life/],
  ['GAIN_VIE',   /gains? (?:\d+|life equal|4 life) life|you gain \d+ life|\blifelink\b|gains life/],
  ['BOOST',      /gets? [+-][\dx]+\/[+-][\dx]+|get \+[\dx]+\/\+[\dx]+/],
  ['VOL',        /\bflying\b/],
  ['PIETINEMENT',/\btrample\b/],
  ['MENACE',     /\bmenace\b|\bintimidate\b/],
  ['IMBLOCABLE', /can't be blocked/],
  ['CELERITE',   /\bhaste\b/],
  ['INDESTRUCTIBLE',/\bindestructible\b/],
  ['LINCEUL',    /\bhexproof\b|\bshroud\b/],
  ['PROTECTION', /protection from|\bward\b|can't be the target/],
  ['ENGAGEMENT', /\btaps? (?:target|all|each|up to)|enter(?:s)? tapped|doesn't untap|tapped and attacking/],
  ['STAX',       /can't (?:cast|attack|block|activate|be cast)|skip your|skip their|no maximum hand size|can't be regenerated/],
  ['TAXE',       /costs? \{\d+\} more|unless (?:that player|they) pays?|may pay \{\d+\}|unless that player pays/],
  ['MIS_AU_CIMETIERE', /put into (?:a|your|their) graveyard from anywhere/],
  ['LTB',            /leaves the battlefield/],
  ['PROLIFERATION',  /\bproliferate\b/],
  ['MARQUEUR_M1M1',  /-1\/-1 counter|\bwither\b/],
  ['MARQUEUR_AUTRE', /(?:charge|loyalty|lore|oil|stun|shield|blood|verse|quest|page|time) counter/],
  ['MARQUEUR_RETIRE',/remove (?:a|an|one|two|\d+|x|all) .{0,25}counters?/],
  ['TRANSFORMATION', /\btransforms?\b|\bdaybound\b|\bnightbound\b/],
  ['FACE_VISIBLE',   /turn(?:s|ed)? .{0,20}face up|\bdisguise\b|\bmorph\b|\bmanifest\b/],
  ['ATTACHEMENT',    /\battach\b|becomes attached|\bequip\b/],
  ['GAIN_CONTROLE',  /gains? control of/],
  ['ENERGIE',        /\{e\}|energy counter/],
  ['EXPERIENCE',     /experience counter/],
  ['MONARQUE',       /\bmonarch\b|take the initiative|\binitiative\b/],
  ['DONJON',         /\bdungeon\b|\bventure\b/],
  ['DE',             /roll (?:a|two|\d+) .{0,12}(?:die|dice)|flip a coin/],
  ['POISON',         /poison counter|\btoxic\b|\binfect\b/],
  ['CYCLE',          /\bcycl(?:e|es|ing)\b/],
  ['REVELATION',     /reveals? (?:a|an|the top|your hand|cards)/],
  ['MIS_EN_BIBLIO',  /(?:shuffles?|puts?) .{0,40}into .{0,15}library|on top of .{0,20}library/],
  ['VIGILANCE',      /\bvigilance\b/],
  ['DEGATS_COMBAT_JOUEUR',  /deals combat damage to a player/],
  ['DEGATS_COMBAT_CREATURE',/deals combat damage to a creature/],
  ['TERRAIN_JOUE',   /play an additional land|plays? a land/],
  ['SEUIL_VIE',      /life total is \d+ or less|has \d+ or less life/],
  ['MAIN_VIDE',      /no cards in (?:your|their) hand/]
];

/* Règles d'extraction : déclencheurs */
const TRIGGER_RULES = [
  ['ETB',      /enter(?:s|ing)\b/],
  ['MORT',     /dies|is put into a graveyard from the battlefield|leaves the battlefield/],
  ['ATTAQUE',  /attacks/],
  ['LANCEMENT',/casts?\b|you cast/],
  ['PIOCHE',   /draws? a card/],
  ['DEFAUSSE', /discards?/],
  ['SACRIFICE',/sacrifices?|exploits/],
  ['TERRAIN',  /land you control enters|land enters/],
  ['GAIN_VIE', /gains? life/],
  ['MARQUEUR', /counters? (?:is|are) put/],
  ['ENTRETIEN',/upkeep|draw step/],
  ['FIN_TOUR', /end step|end of turn/],
  ['DEGATS',   /deals damage|deals combat damage/],
  ['MANA',     /tapped for mana/],
  ['ENGAGEMENT',/activate an ability|becomes tapped/],
  ['TRESOR',   /treasure/],
  ['ETB_CIMETIERE',['enters'],/enters .{0,40}from (?:a|your|their) graveyard/],
  ['ETB_EXIL',     ['enters'],/enters .{0,40}from exile/],
  ['ETB_BIBLIO',   ['enters'],/enters .{0,40}from .{0,20}library/],
  ['LTB',          /leaves the battlefield/],
  ['MIS_AU_CIMETIERE',/put into (?:a|your|their) graveyard from anywhere/],
  ['TERRAIN_JOUE', /plays? a land/],
  ['BLOCAGE',      /\bblocks\b/],
  ['DEVIENT_BLOQUEE',/becomes blocked/],
  ['ATTAQUE_SEULE',/attacks alone/],
  ['DEGATS_COMBAT_JOUEUR',/deals combat damage to a player|deals damage to a player/],
  ['DEGATS_COMBAT_CREATURE',/deals combat damage to a creature/],
  ['DEBUT_COMBAT', /beginning of combat/],
  ['FIN_COMBAT',   /end of combat/],
  ['ETAPE_PIOCHE', /draw step/],
  ['PHASE_PRINCIPALE',/main phase/],
  ['DEBUT_TOUR',   /beginning of .{0,25}turn/],
  ['TOUR_SUPPLEMENTAIRE',/extra turn/],
  ['CYCLE',        /\bcycles?\b/],
  ['REVELATION',   /reveals?/],
  ['PERTE_VIE',    /loses? life|loses? \d+ life/],
  ['DEGATS_SUBIS', /is dealt damage/],
  ['POISON',       /poison counter/],
  ['SEUIL_VIE',    /life total is \d+ or less|has \d+ or less life/],
  ['MAIN_VIDE',    /no cards in (?:your|their) hand/],
  ['MARQUEUR_RETIRE',/remove .{0,25}counters?/],
  ['DEVIENT_CIBLE',/becomes the target/],
  ['CAPACITE_ACTIVEE',/activates? an ability/],
  ['CAPACITE_DECLENCHEE',/triggered ability .{0,25}triggers/],
  ['TRANSFORMATION',/transforms?/],
  ['FACE_VISIBLE', /turned face up/],
  ['ATTACHEMENT',  /becomes attached/],
  ['GAIN_CONTROLE',/gains? control/],
  ['ENERGIE',      /\{e\}/],
  ['EXPERIENCE',   /experience counter/],
  ['MONARQUE',     /\bmonarch\b|\binitiative\b/],
  ['DONJON',       /\bdungeon\b|\bventure\b/],
  ['DE',           /roll .{0,12}(?:die|dice)|flip a coin/],
  ['SORT_RESOUT',  /spell resolves/],
  ['CHAPITRE_SAGA',/\bchapter\b/],
  ['JOUR_NUIT',    /day becomes night|night becomes day/],
  ['LANCEMENT_SOI',/cast this spell/]
];
